"""compliance_alerts

Revision ID: 2ef0f81e36d8
Revises: 7f0b005f6350
Create Date: 2026-10-05 13:11:15.390085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef0f81e36d8'
down_revision: Union[str, Sequence[str], None] = '7f0b005f6350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(length=34), nullable=False),
    sa.Column('opened_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_compliance_alerts_account_id'), 'compliance_alerts', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_alerts_account_id'), table_name='compliance_alerts')
    op.drop_table('compliance_alerts')
    # ### end Alembic commands ###
