"""init chat tables

Revision ID: 69f8b152bbd9
Revises:
Create Date: 2026-09-17 16:24:32.711886

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "69f8b152bbd9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
